[build]
  base = "vega-app"
  command = "npm run build"
  publish = "vega-app/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
